### ISSUE TITLE
Question about header_path.patch

### ISSUE THREAD

**Issue by daravi** [UncannyBingo/conan-mongo-c-driver#4]
Hi I made a question issue on bin-crafters:
https://github.com/bincrafters/community/issues/819

Are you still maintaining this package? I was wondering if you know what is the header_path.patch file for and if it is still needed for 1.14.0?

**Comment by Croydon** [comment]
@DEGoodmanWilson brought this recipe into Bincrafters. So if @DEGoodmanWilson wants to continue to maintain it, it will happen in Bincrafters :)

**Comment by UncannyBingo** [comment]
Howdy! I'll follow up in Bincrafters.
